CREATE TABLE hosts (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text        NOT NULL UNIQUE,
    kind       text        NOT NULL CHECK (kind IN ('host', 'vps')),
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO hosts (name, kind) VALUES ('ATLAS', 'host')
ON CONFLICT (name) DO NOTHING;
