CREATE TABLE devices (
    id                integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text        NOT NULL CHECK (name <> ''),
    credential_id     bytea       NOT NULL UNIQUE,
    public_key        bytea       NOT NULL,
    sign_count        bigint      NOT NULL DEFAULT 0 CHECK (sign_count >= 0),
    aaguid            bytea       NOT NULL DEFAULT '\x'::bytea,
    transports        text[]      NOT NULL DEFAULT '{}',
    attestation_type  text        NOT NULL DEFAULT 'none',
    attestation_fmt   text        NOT NULL DEFAULT 'none',
    backup_eligible   boolean     NOT NULL DEFAULT false,
    backup_state      boolean     NOT NULL DEFAULT false,
    created_at        timestamptz NOT NULL DEFAULT now(),
    last_seen         timestamptz
);
