CREATE TABLE enroll_codes (
    id         integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash  text        NOT NULL,
    source     text        NOT NULL CHECK (source IN ('console', 'panel')),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    used_at    timestamptz
);

CREATE TABLE owner (
    id          integer     PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    user_handle bytea       NOT NULL CHECK (length(user_handle) = 32),
    created_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO owner (user_handle) VALUES (
    decode(replace(gen_random_uuid()::text, '-', ''), 'hex') ||
    decode(replace(gen_random_uuid()::text, '-', ''), 'hex')
);
