CREATE TABLE rules (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text    NOT NULL UNIQUE,
    subject    text    NOT NULL,
    target     text,
    op         text    NOT NULL CHECK (op IN ('>', '>=', '<', '<=', '=')),
    threshold  double precision NOT NULL,
    for_sec    integer NOT NULL CHECK (for_sec >= 10),
    severity   text    NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    enabled    boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE alerts (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id   integer NOT NULL REFERENCES rules (id) ON DELETE CASCADE,
    subject   text    NOT NULL,
    severity  text    NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    opened_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz,
    last_seen timestamptz NOT NULL DEFAULT now(),
    value      double precision,
    worst      double precision,
    payload   jsonb   NOT NULL DEFAULT '{}'
);

CREATE UNIQUE INDEX alerts_one_open ON alerts (rule_id, subject) WHERE closed_at IS NULL;

CREATE INDEX alerts_recent ON alerts (opened_at DESC);

INSERT INTO rules (name, subject, target, op, threshold, for_sec, severity) VALUES
    ('Container eats CPU',            'container.cpu_pct',    NULL, '>',  90,  300, 'warning'),
    ('Container hit its RAM limit',   'container.mem_pct',    NULL, '>',  90,  300, 'warning'),
    ('Host CPU is loaded',            'host.cpu_pct',         NULL, '>',  90,  600, 'warning'),
    ('Host memory is running out',    'host.mem_pct',         NULL, '>',  90,  600, 'warning'),
    ('Host went into swap',           'host.swap_bytes',      NULL, '>',  1073741824, 600, 'warning'),
    ('CPU run queue',                 'host.load1',           NULL, '>',  32,  600, 'info'),
    ('Disk is filling up',            'disk.used_pct',        NULL, '>',  85,  600, 'warning'),
    ('Disk is almost full',           'disk.used_pct',        NULL, '>',  95,  300, 'critical'),
    ('Running on battery',            'ups.on_battery',       NULL, '=',  1,    60, 'critical'),
    ('Battery charge is low',         'ups.charge_pct',       NULL, '<',  50,   60, 'critical'),
    ('The battery needs replacing',   'ups.replace_battery',  NULL, '=',  1,   300, 'warning'),
    ('The claude limit is running out','session.pct',          NULL, '>',  85,  300, 'warning');
