CREATE TABLE actions (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          timestamptz NOT NULL DEFAULT now(),
    device_id   integer,
    device_name text        NOT NULL,
    kind        text        NOT NULL CHECK (kind <> ''),
    target      text        NOT NULL,
    params      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    result      text        CHECK (result IS NULL OR result IN ('ok', 'failed', 'timeout', 'rejected')),
    error       text,
    duration_ms integer     CHECK (duration_ms IS NULL OR duration_ms >= 0),
    finished_at timestamptz,
    CONSTRAINT actions_result_complete CHECK (
        (result IS NULL AND error IS NULL AND duration_ms IS NULL AND finished_at IS NULL)
        OR (result IS NOT NULL AND finished_at IS NOT NULL)
    )
);

CREATE INDEX actions_recent ON actions (ts DESC);

CREATE INDEX actions_by_target ON actions (target, ts DESC);

CREATE FUNCTION actions_append_only() RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'the action log cannot be changed: record % is not deleted', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF OLD.result IS NOT NULL THEN
        RAISE EXCEPTION 'action % is already finished (%), the outcome is not rewritten', OLD.id, OLD.result
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.id          IS DISTINCT FROM OLD.id
    OR NEW.ts          IS DISTINCT FROM OLD.ts
    OR NEW.device_id   IS DISTINCT FROM OLD.device_id
    OR NEW.device_name IS DISTINCT FROM OLD.device_name
    OR NEW.kind        IS DISTINCT FROM OLD.kind
    OR NEW.target      IS DISTINCT FROM OLD.target
    OR NEW.params      IS DISTINCT FROM OLD.params THEN
        RAISE EXCEPTION 'the action log cannot be changed: only the outcome of record % is editable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER actions_append_only
    BEFORE UPDATE OR DELETE ON actions
    FOR EACH ROW EXECUTE FUNCTION actions_append_only();
