CREATE TABLE probes (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text    NOT NULL UNIQUE,
    kind         text    NOT NULL CHECK (kind IN ('tcp', 'http')),
    target       text    NOT NULL,
    interval_sec integer NOT NULL CHECK (interval_sec >= 10),
    timeout_sec  integer NOT NULL CHECK (timeout_sec BETWEEN 1 AND 60),
    runner       text    NOT NULL DEFAULT 'service' CHECK (runner IN ('service', 'agent')),
    enabled      boolean NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE probe_results (
    ts         timestamptz NOT NULL,
    probe_id   integer NOT NULL REFERENCES probes (id) ON DELETE CASCADE,
    ok         boolean NOT NULL,
    latency_ms integer,
    outcome    text NOT NULL CHECK (outcome IN ('ok', 'network', 'timeout', 'status', 'config')),
    error      text,
    PRIMARY KEY (probe_id, ts)
) PARTITION BY RANGE (ts);

CREATE INDEX probe_results_recent ON probe_results (probe_id, ts DESC);

INSERT INTO partition_config (relname, step_unit, keep) VALUES ('probe_results', 'day', '30 days');
SELECT ensure_partitions('7 days');

INSERT INTO probes (name, kind, target, interval_sec, timeout_sec) VALUES
    ('API Anthropic', 'tcp', 'api.anthropic.com:443', 60, 5),
    ('API Google',    'tcp', 'www.googleapis.com:443', 60, 5),
    ('API Telegram',  'tcp', 'api.telegram.org:443',  60, 5);

INSERT INTO rules (name, subject, target, op, threshold, for_sec, severity) VALUES
    ('A probe keeps failing', 'probe.fail_streak', NULL, '>=', 3, 10, 'warning');
