CREATE TABLE IF NOT EXISTS profiles (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE CHECK (name <> ''),
    config_dir text NOT NULL CHECK (config_dir LIKE '/%'),
    prefix text NOT NULL DEFAULT '' CHECK (prefix = '' OR prefix LIKE '/%'),
    sort integer NOT NULL DEFAULT 0,
    launch jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(launch) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profile_groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id integer NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    name       text    NOT NULL CHECK (name <> ''),
    sort       integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS profile_groups_order ON profile_groups (profile_id, sort, id);

CREATE TABLE IF NOT EXISTS profile_projects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL REFERENCES profile_groups (id) ON DELETE RESTRICT,
    name text NOT NULL CHECK (name <> ''),
    path text NOT NULL CHECK (path LIKE '/%'),
    session_name text NOT NULL DEFAULT '',
    sort   integer NOT NULL DEFAULT 0,
    launch jsonb   NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(launch) = 'object')
);

CREATE INDEX IF NOT EXISTS profile_projects_order ON profile_projects (group_id, sort, id);

DO $$
DECLARE
    seq text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'monitor_app') THEN
        RAISE NOTICE 'there is no role monitor_app — no rights are issued (see deploy/create-app-role.sh)';
        RETURN;
    END IF;
    GRANT SELECT, INSERT, UPDATE, DELETE ON profiles, profile_groups, profile_projects TO monitor_app;
    FOREACH seq IN ARRAY ARRAY[
        pg_get_serial_sequence('profiles', 'id'),
        pg_get_serial_sequence('profile_groups', 'id'),
        pg_get_serial_sequence('profile_projects', 'id')
    ] LOOP
        IF seq IS NOT NULL THEN
            EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE ' || seq || ' TO monitor_app';
        END IF;
    END LOOP;
    RAISE NOTICE 'the rights of monitor_app on the profile map are issued';
END $$;
