CREATE TABLE profile_journal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at timestamptz NOT NULL DEFAULT now(),
    actor text NOT NULL DEFAULT '',
    entity text NOT NULL CHECK (entity IN ('contour', 'group', 'project')),
    entity_id integer NOT NULL,
    name text NOT NULL DEFAULT '',
    op text NOT NULL CHECK (op IN ('create', 'update', 'delete')),
    changes jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(changes) = 'array'),
    row_before jsonb,
    undoes bigint REFERENCES profile_journal (id) ON DELETE SET NULL,
    undone_at timestamptz
);

CREATE INDEX profile_journal_at ON profile_journal (at DESC, id DESC);
