"""Records the human did not write, although they lie among their prompts."""
import re

from .limits import MAX_NOTE, MAX_TEXT, cut
from .mail import mails


NOTES = (
    ("[Request interrupted", "the human interrupted the answer"),
    ("This session is being continued from a previous conversation",
     "the context was compacted, the conversation continues from a summary"),
)

SKIP = (
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user while running local commands",
    "<command-message>",
    "<command-args>",
    "is already loaded above",
)

COMMAND_RE = re.compile(r"<command-name>\s*(/[^<\s]+)")
COMMAND_ARGS_RE = re.compile(r"<command-args>(.*?)</command-args>", re.S)

COMMAND_OUT_RE = re.compile(r"<local-command-std(out|err)>(.*)</local-command-std\1>", re.S)
ANSI_RE = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")


def command_out(text):
    """Returns the note text for a slash command answer, or None when it is not one."""
    found = COMMAND_OUT_RE.search(text)
    if not found:
        return None
    said = ANSI_RE.sub("", found.group(2)).strip()
    body, trimmed = cut(said, MAX_NOTE)
    return body + "…" if trimmed else body


TASK_NOTE_RE = re.compile(r"<task-notification>(.*?)</task-notification>", re.S)
TASK_FIELD_RE = re.compile(r"<([\w-]+)>([^<]*)</\1>")


def task_done(text):
    """Returns the finished background task as (call id, status, what it was about)."""
    found = TASK_NOTE_RE.search(text)
    if not found:
        return None
    fields = dict(TASK_FIELD_RE.findall(found.group(1)))
    use = (fields.get("tool-use-id") or "").strip()
    if not use:
        return None
    return use, (fields.get("status") or "").strip(), (fields.get("summary") or "").strip()


DELIVERY_MARK = "[Cross-session delivery notice]"
DELIVERY = (
    ("held for the recipient user's approval", "the letter waits for the recipient to approve it"),
    ("denied by the recipient user", "the recipient denied the letter"),
    ("not approved before expiry", "the letter was not approved — the time ran out"),
    ("approved and released", "the letter was delivered"),
    ("refused", "the session accepts no letters"),
    ("dropped at", "the letter was not delivered"),
)


def delivery(text):
    """Returns a short note about the fate of a letter, empty when it is not one."""
    if DELIVERY_MARK not in text:
        return ""
    for mark, said in DELIVERY:
        if mark in text:
            return said
    return text.replace(DELIVERY_MARK, "").strip()


def service(text, at, pos):
    """Returns feed items for a record the human did not write, or None for plain text."""
    said = delivery(text)
    if said:
        return [{"role": "note", "text": said, "at": at, "pos": pos}]
    if "<teammate-message" in text or "<cross-session-message" in text:
        out = []
        for who, source, said in mails(text):
            body, trimmed = cut(said, MAX_TEXT)
            out.append({"role": "mail", "from": who, "source": source,
                        "text": body, "cut": trimmed, "at": at, "pos": pos})
        return out

    if "<task-notification>" in text:
        done = task_done(text)
        if not done:
            return []
        use, status, summary = done
        return [{"role": "taskdone", "use": use, "status": status,
                 "summary": summary, "at": at, "pos": pos}]

    return None


def classify(text):
    """Returns what the prompt is as (role, what to show)."""
    head = text[:200]

    command = COMMAND_RE.search(head)
    if command:
        args = COMMAND_ARGS_RE.search(text)
        typed = f"{command.group(1)} {args.group(1)}" if args else command.group(1)
        return "me", typed.strip()

    said = command_out(text)
    if said is not None:
        return ("note", said) if said else ("skip", "")

    for mark, note in NOTES:
        if mark in head:
            return "note", note

    for mark in SKIP:
        if mark in head:
            return "skip", ""

    return "me", text


# The word inside the note is not text but a key: the note is written into
# the transcript by whoever sends the reply, and transcripts written earlier
# are still read. A translated pattern would stop stripping them.
PANEL_NOTE = re.compile(r"^\[владелец[^\]\n]*\]\s*")


def strip_panel_note(text):
    """Returns the prompt without the service note the panel adds."""
    return PANEL_NOTE.sub("", text, count=1)
